"""persist analysis artifacts and video key

Revision ID: 8738bcd0e60b
Revises: f856cb2f866a
Create Date: 2026-09-20 17:15:35.602624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8738bcd0e60b'
down_revision: Union[str, Sequence[str], None] = 'f856cb2f866a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('observations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('video_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'video_key')
    op.drop_column('jobs', 'observations')
    op.drop_column('jobs', 'metrics')
    # ### end Alembic commands ###
